<a href="https://colab.research.google.com/github/powersurge8891/Association_Rule_Mining/blob/main/Grocery_Store_item_placement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data and Libraries

In [1]:
%cd /content/drive/MyDrive/Data Mining for Business in Python/6. Association Rule Learning

/content/drive/MyDrive/Data Mining for Business in Python/6. Association Rule Learning

In [2]:
#libraries
import pandas as pd
from mlxtend.frequent_patterns import association_rules, apriori

In [3]:
data= pd.read_csv('groceries.csv')

In [4]:
data.head()

             Item 1               Item 2  ... Item 21 Item 22
0      citrus fruit  semi-finished bread  ...     NaN     NaN
1    tropical fruit               yogurt  ...     NaN     NaN
2        whole milk                  NaN  ...     NaN     NaN
3         pip fruit               yogurt  ...     NaN     NaN
4  other vegetables           whole milk  ...     NaN     NaN

[5 rows x 22 columns]

In [5]:
'''
The data above shows the number of items bought by each customer in a grocery store.
The first customer( customer 0), boought citrus fruit, semi-finished bread, margrine etc.
'''

'\nThe data above shows the number of items bought by each customer in a grocery store.\nThe first customer( customer 0), boought citrus fruit, semi-finished bread, margrine etc.\n'

In [6]:
data.shape

(9835, 22)

In [7]:
transaction=[]
for i in range(0, 9835):

  transaction.append(
      [str(data.values[i, j])
  for j in range(0,22)]
  
  )

In [8]:
#Encoding transactions
from mlxtend.preprocessing import TransactionEncoder

In [10]:
te= TransactionEncoder()

In [12]:
tranEncoded= te.fit_transform(transaction)

In [14]:
te_trans=pd.DataFrame(tranEncoded, columns=te.columns_)

In [15]:
te_trans.sample(3)

      Instant food products  UHT-milk  ...  yogurt  zwieback
4075                  False     False  ...   False     False
1112                  False     False  ...   False     False
597                   False     False  ...    True     False

[3 rows x 170 columns]

In [17]:
te_trans.drop(columns='nan', inplace=True)

In [18]:
model= apriori(te_trans, min_support=0.03, use_colnames=True)

In [21]:
result= association_rules(model, min_threshold=0.3)
result.sort_values(by='lift', ascending=False)

             antecedents         consequents  ...  leverage  conviction
2      (root vegetables)  (other vegetables)  ...  0.026291    1.426693
8              (sausage)        (rolls/buns)  ...  0.013324    1.210344
3       (tropical fruit)  (other vegetables)  ...  0.015589    1.225796
12  (whipped/sour cream)        (whole milk)  ...  0.013916    1.352735
10     (root vegetables)        (whole milk)  ...  0.021056    1.350401
5               (yogurt)  (other vegetables)  ...  0.016424    1.170929
11      (tropical fruit)        (whole milk)  ...  0.015486    1.247252
13              (yogurt)        (whole milk)  ...  0.020379    1.244132
7            (pip fruit)        (whole milk)  ...  0.010767    1.236375
4     (other vegetables)        (whole milk)  ...  0.025394    1.214013
6               (pastry)        (whole milk)  ...  0.010516    1.188729
1         (citrus fruit)        (whole milk)  ...  0.009355    1.179008
0        (bottled water)        (whole milk)  ...  0.006051    1.079452
9           (rolls/buns)        (whole milk)  ...  0.009636    1.075696

[14 rows x 9 columns]